export const PROFILE_FETCH_CONTACTS_START = 'PROFILE_FETCH_CONTACTS_START';
export const PROFILE_FETCH_CONTACTS_STOP = 'PROFILE_FETCH_CONTACTS_STOP';
export const PROFILE_FILL_CONTACTS = 'PROFILE_FILL_CONTACTS';
export const PROFILE_SET_FETCHING_ERROR = 'PROFILE_SET_FETCHING_ERROR';
export const PROFILE_RESET_ERROR = 'PROFILE_RESET_ERROR';

export const PROFILE_FETCH_ASYNC = 'PROFILE_FETCH_ASYNC';
