// get contacts
export const PROFILE_FETCH_CONTACTS_START = 'PROFILE_FETCH_CONTACTS_START';
export const PROFILE_FETCH_CONTACTS_STOP = 'PROFILE_FETCH_CONTACTS_STOP';
export const PROFILE_FILL_CONTACTS = 'PROFILE_FILL_CONTACTS';
export const PROFILE_SET_FETCHING_ERROR = 'PROFILE_SET_FETCHING_ERROR';
export const PROFILE_RESET_ERROR = 'PROFILE_RESET_ERROR';

export const PROFILE_FETCH_ASYNC = 'PROFILE_FETCH_ASYNC';

// delete contact
export const PROFILE_DELETE_CONTACT_START = 'PROFILE_DELETE_CONTACT_START';
export const PROFILE_DELETE_CONTACT_STOP = 'PROFILE_DELETE_CONTACT_STOP';
export const PROFILE_DELETE_CONTACT_FILL = 'PROFILE_DELETE_CONTACT_FILL';
export const PROFILE_SET_DELETING_ERROR = 'PROFILE_SET_DELETING_ERROR';
export const PROFILE_DELETE_ERROR_RESET = 'PROFILE_DELETE_ERROR_RESET';

export const PROFILE_DELETE_CONTACT_ASYNC = 'PROFILE_DELETE_CONTACT_ASYNC';

// create contact
export const PROFILE_CREATE_CONTACT_START = 'PROFILE_CREATE_CONTACT_START';
export const PROFILE_CREATE_CONTACT_STOP = 'PROFILE_CREATE_CONTACT_STOP';
export const PROFILE_CREATE_CONTACT_FILL = 'PROFILE_CREATE_CONTACT_FILL';
export const PROFILE_SET_CREATING_ERROR = 'PROFILE_SET_CREATING_ERROR';
export const PROFILE_CREATE_ERROR_RESET = 'PROFILE_CREATE_ERROR_RESET';

export const PROFILE_CREATE_CONTACT_ASYNC = 'PROFILE_CREATE_CONTACT_ASYNC';

// search contacts
export const PROFILE_SEARCH_CONTACT_START = 'PROFILE_SEARCH_CONTACT_START';
export const PROFILE_SEARCH_CONTACT_STOP = 'PROFILE_SEARCH_CONTACT_STOP';
export const PROFILE_SEARCH_CONTACT_FILL = 'PROFILE_SEARCH_CONTACT_FILL';

export const PROFILE_SEARCH_CONTACT_ASYNC = 'PROFILE_SEARCH_CONTACT_ASYNC';
