export const REGISTRATION_FETCH_START = 'REGISTRATION_FETCH_START';
export const REGISTRATION_FETCH_STOP = 'REGISTRATION_FETCH_STOP';
export const REGISTRATION_FILL = 'REGISTRATION_FILL';
export const REGISTRATION_SET_FETCHING_ERROR = 'REGISTRATION_SET_FETCHING_ERROR';
export const REGISTRATION_RESET_ERROR = 'REGISTRATION_RESET_ERROR';

export const REGISTRATION_FETCH_ASYNC = 'REGISTRATION_FETCH_ASYNC';
