export const LOGIN_FETCH_START = 'LOGIN_FETCH_START';
export const LOGIN_FETCH_STOP = 'LOGIN_FETCH_STOP';
export const LOGIN_FILL = 'LOGIN_FILL';
export const LOGIN_SET_FETCHING_ERROR = 'LOGIN_SET_FETCHING_ERROR';
export const LOGIN_RESET_ERROR = 'LOGIN_RESET_ERROR';

export const LOGIN_FETCH_ASYNC = 'LOGIN_FETCH_ASYNC';
